kind = "web"
previewPath = "/"
title = "Natural Calamity Detector"
version = "1.0.0"
id = "artifacts/calamity-detector"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18762

[services.development]
run = "pnpm --filter @workspace/calamity-detector run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/calamity-detector", "run", "build" ]
publicDir = "artifacts/calamity-detector/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18762"
BASE_PATH = "/"
